name: frontend_app_task
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  package_info_plus: ^8.3.0
  bottom_nav_layout: ^3.0.10
  flutter_svg: ^2.1.0
  icons_plus: ^5.0.0
  flutter_form_builder: ^10.0.1
  scroll_date_picker: ^3.8.0
  intl: ^0.20.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  app_settings: ^6.1.1
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

