// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy3jEUfDz3Gt-jUdlHTQ_13u30P-9OCwY',
    appId: '1:517094763462:web:52cd8a74e44c2fb35760c7',
    messagingSenderId: '517094763462',
    projectId: 'node-js-task-notification',
    authDomain: 'node-js-task-notification.firebaseapp.com',
    storageBucket: 'node-js-task-notification.firebasestorage.app',
    measurementId: 'G-1485N0N5F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdpXpF23iplT_Rz8SUuyBsLVtuCIXj7C0',
    appId: '1:517094763462:android:ec5dcf98d906f8005760c7',
    messagingSenderId: '517094763462',
    projectId: 'node-js-task-notification',
    storageBucket: 'node-js-task-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiQkc9m4Na7qLLItBOt9MzOMl-JZJ4ffY',
    appId: '1:517094763462:ios:d3a6a6ae642568fd5760c7',
    messagingSenderId: '517094763462',
    projectId: 'node-js-task-notification',
    storageBucket: 'node-js-task-notification.firebasestorage.app',
    iosBundleId: 'com.example.frontendAppTask',
  );
}
